name: audio_book
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.3
  lottie: ^2.7.0
  just_audio: ^0.9.36
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.7
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  device_preview: ^1.1.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.3.1
  google_sign_in: ^6.2.1
  #  animated_bottom_navigation_bar: ^1.3.3
  #  flutter_facebook_auth: ^6.1.1
  shared_preferences: ^2.2.2
  firebase_app_check: ^0.2.1+17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/audios/

  fonts:
    - family: Uni Neue
      fonts:
        - asset: assets/fonts/uni_neue/uni_neue_trial_thin.ttf
          weight: 100
        - asset: assets/fonts/uni_neue/uni_neue_trial_light.ttf
          weight: 200
        - asset: assets/fonts/uni_neue/uni_neue_trial_book.ttf
          weight: 300
        - asset: assets/fonts/uni_neue/uni_neue_trial_regular.ttf
          weight: 400
        - asset: assets/fonts/uni_neue/uni_neue_trial_bold.ttf
          weight: 500
        - asset: assets/fonts/uni_neue/uni_neue_trial_heavy.ttf
          weight: 600
        - asset: assets/fonts/uni_neue/uni_neue_trial_black.ttf
          weight: 700