// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC15kDNvVflX2hCXyAZw6BhV9eILRpVjsQ',
    appId: '1:1080458873674:android:4f5ba5b01b7bcd1d83cfb3',
    messagingSenderId: '1080458873674',
    projectId: 'audiobook-17d1d',
    storageBucket: 'audiobook-17d1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARBXBt3Ly9yA6lpIIHIgWVSG8dyU5BrBQ',
    appId: '1:1080458873674:ios:131d82a6caeb3acc83cfb3',
    messagingSenderId: '1080458873674',
    projectId: 'audiobook-17d1d',
    storageBucket: 'audiobook-17d1d.appspot.com',
    androidClientId: '1080458873674-ihc8glt3kkngnah87jm0msa48l93kodu.apps.googleusercontent.com',
    iosClientId: '1080458873674-jfq7dvt9a08teeeu0r4tfip9g2l40hlg.apps.googleusercontent.com',
    iosBundleId: 'com.example.audioBook',
  );
}
